// <auto-generated />
using API_Gerenciador_de_tarefas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Gerenciador_de_tarefas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240405222511_PopulandoStatus")]
    partial class PopulandoStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_Gerenciador_de_tarefas.Models.Gerenciador", b =>
                {
                    b.Property<int>("GerenciadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GerenciadorId"));

                    b.Property<string>("NomeTarefa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StatusId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("GerenciadorId");

                    b.HasIndex("StatusId");

                    b.ToTable("Gerenciador");
                });

            modelBuilder.Entity("API_Gerenciador_de_tarefas.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusTarefa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("API_Gerenciador_de_tarefas.Models.Gerenciador", b =>
                {
                    b.HasOne("API_Gerenciador_de_tarefas.Models.Status", "Status")
                        .WithMany("Gerenciador")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("API_Gerenciador_de_tarefas.Models.Status", b =>
                {
                    b.Navigation("Gerenciador");
                });
#pragma warning restore 612, 618
        }
    }
}
